version: '3.9'

services:
  w2:
    build:
      context: .
      dockerfile: Dockerfile
    image: w2
    container_name: w2
    restart: unless-stopped
    ports:
      - "8080:8080"
    volumes:
      - ./watchtower-configuration.json:/app/watchtower-configuration.json:ro
      - /var/log/watchtower:/var/log/watchtower
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - TZ=Europe/Moscow
